app:
  port: 6000
api:
  version: "1.0"

scope:
  videoCreate: https://api.supersoccer.tv/videos/videos.create
  videoRead: https://api.supersoccer.tv/videos/videos.read
  videoUpdate: https://api.supersoccer.tv/videos/videos.update
  videoDelete: https://api.supersoccer.tv/videos/videos.delete
  videoEmbed: https://api.supersoccer.tv/videos/videos.embed
  playlistCreate: https://api.supersoccer.tv/videos/playlists.create
  playlistRead: https://api.supersoccer.tv/videos/playlists.read
  playlistUpdate: https://api.supersoccer.tv/videos/playlists.update
  playlistDelete: https://api.supersoccer.tv/videos/playlists.delete
  programGuideRead: https://api.supersoccer.tv/videos/program-guide.read
  videoQualityRead: https://api.supersoccer.tv/videos/qualities.read
  videoReadFira: https://polytron.supersoccer.tv/videos/videos.read
  userReadGlobal: https://internal.supersoccer.tv/subscriptions/users.read.global

playlist:
  free: s-free

db:
  host: 127.0.0.1
  port: 3306
  dialect: mysql
  name: video
  user: umar  
  password: umarsstv

cache:
  ttl: 30

redis:
  host: 127.0.0.1
  port: 6379
  prefix: videos
  ttl: 3600

sentry:
  dsn: DSN

Harmonics: 
  script: /path/to/videos-api/src/scripts/akamai_token_v2.py 
  key: KEY
  expired: 3600

Bein:
  script: /path/to/videos-api/src/scripts/akamai_token_v2.py 
  key: KEY
  expired: 3600

Dawan:
  key: KEY
  expired: 3600

apiClient:
  domain: https://api.supersabar.com
  key: KEY
  secret: SECRET
